version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build
    depends_on:
      - nginx
 
